spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/cloud_health?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: diao
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8081
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #实体类存放路径
  type-aliases-package: cn.lcdiao.springbootmybatis.entity
